service: rrandallpainter-api
plugins:
  - serverless-dotenv-plugin
  - serverless-apigw-binary
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors:
            origin: 'http://localhost:3000'
            allowCredentials: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors:
            origin: 'http://localhost:3000'
            allowCredentials: true
custom:
  apigwBinary:
    types:           #list of mime-types
      - 'multipart/form-data'
      - 'image/jpeg'
      - 'image/png'
      - 'image/gif'
      - 'image/bmp'
      - 'text/html'